In [36]:
import pandas as pd 

df = pd.read_csv("bank.csv.xls") 
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [37]:
education_mode = df['education'].mode()[0]
df['education'] = df['education'].fillna(education_mode)
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [38]:
df = pd.get_dummies(df, columns=['marital', 'job', 'housing'], drop_first=True)
df.head()

,age,education,default,balance,loan,contact,day,month,duration,campaign,...,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,housing_yes
0,59,secondary,no,2343,no,unknown,5,may,1042,1,...,False,False,False,False,False,False,False,False,False,True
1,56,secondary,no,45,no,unknown,5,may,1467,1,...,False,False,False,False,False,False,False,False,False,False
2,41,secondary,no,1270,no,unknown,5,may,1389,1,...,False,False,False,False,False,False,True,False,False,True
3,55,secondary,no,2476,no,unknown,5,may,579,1,...,False,False,False,False,True,False,False,False,False,True
4,54,tertiary,no,184,no,unknown,5,may,673,2,...,False,False,False,False,False,False,False,False,False,False

In [39]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
df['balance'] = scaler.fit_transform(df[['balance']])
df.head()

,age,education,default,balance,loan,contact,day,month,duration,campaign,...,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,housing_yes
0,59,secondary,no,0.104371,no,unknown,5,may,1042,1,...,False,False,False,False,False,False,False,False,False,True
1,56,secondary,no,0.078273,no,unknown,5,may,1467,1,...,False,False,False,False,False,False,False,False,False,False
2,41,secondary,no,0.092185,no,unknown,5,may,1389,1,...,False,False,False,False,False,False,True,False,False,True
3,55,secondary,no,0.105882,no,unknown,5,may,579,1,...,False,False,False,False,True,False,False,False,False,True
4,54,tertiary,no,0.079851,no,unknown,5,may,673,2,...,False,False,False,False,False,False,False,False,False,False

In [40]:
df.to_csv("bank.csv.xls.final", index=False)